### ISSUE TITLE
Advanced FPS Counter copyright infringement

### ISSUE THREAD

**Issue by DmitriyYukhanov** [cosmos53076/QuickUnity#1]
Hey, cosmos53076!

I'm Dmitriy Yukhanov, author of the Advanced FPS Counter plugin for Unity.

Thanks for purchasing Advanced FPS Counter and for using it in your project(s), I hope it goes well!
But unfortunately, it's not allowed to share it anywhere, as it violates Asset Store Terms of Service and EULA (http://unity3d.com/ru/legal/as_terms), APPENDIX 1, sections 5 & 9 and my own copyrights.

And what is more upset, you have to totally vanish it from the repo, from all commits, which means you have to completely remove repo from the GitHub =(

I hope for the understanding and I'll come back in few days and submit DMCA Takedown Notice if my asset will still be here.

I'm sorry and thank you for your understanding!

**Comment by cosmos53076** [comment]
Hey, Dmitriy
I am so sorry for this. I will remove it right now. Thanks for your reminding.

2016-03-27 

cosmos53076 



发件人："Dmitriy [focus] Yukhanov" <notifications@github.com>
发送时间：2016-03-27 19:32
主题：[QuickUnity] Advanced FPS Counter copyright infringement (#1)
收件人："cosmos53076/QuickUnity"<QuickUnity@noreply.github.com>
抄送：

Hey, cosmos53076!
I'm Dmitriy Yukhanov, author of the Advanced FPS Counter plugin for Unity.
Thanks for purchasing Advanced FPS Counter and for using it in your project(s), I hope it goes well!
But unfortunately, it's not allowed to share it anywhere, as it violates Asset Store Terms of Service and EULA (http://unity3d.com/ru/legal/as_terms), APPENDIX 1, sections 5 & 9 and my own copyrights.
And what is more upset, you have to totally vanish it from the repo, from all commits, which means you have to completely remove repo from the GitHub =(
I hope for the understanding and I'll come back in few days and submit DMCA Takedown Notice if my asset will still be here.
I'm sorry and thank you for your understanding!

**Comment by cosmos53076** [comment]
I fixed it already. Thanks for reminding!

**Comment by DmitriyYukhanov** [comment]
Hey, 

Thanks for your quick reaction, but unfortunately it's still available in all previous commits, like this:
https://github.com/cosmos53076/QuickUnity/tree/f51dbcd200477abee5303b82052e85a38db0d81e/Assets/CodeStage/AdvancedFPSCounter

I'm afraid the only one way to vanish it from the repo is to remove the repo completely.
